# Generated by Django 5.2.5 on 2025-09-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libraries',
            new_name='Librarian',
        ),
    ]
